<?php

namespace SoftUniBundle\Repository;

/**
 * SellBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellBookRepository extends \Doctrine\ORM\EntityRepository
{
}
